name: CI

on: pull_request

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Packages
        run: yarn install --production=false
        
      - name: Lint
        run: yarn lint

      
